spring:
  application:
    name: poc-logger
  # zipkin:
  #   enabled: true
  #   baseUrl: https://webhook.site/1f66b8f8-d524-4a61-9ef9-b481b3cd53da
  #   sender:
  #     type: web
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
      percentage: 1.0
